sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # SonataUserBundle
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
    dashboard:
        blocks:
            left:
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Order, Shop]

            right:
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Content, Config, sonata_user]

    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role

sonata_user:
    security_acl: false
    manager_type: orm

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

pix_sortable_behavior:
    db_driver: orm
    position_field:
        default: order